TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this

DB += ioLogikCommon.template
DB += DI_alarm.template
DB += AI_alarm.template
DB += AO_scaling.template
DB += AO_scaling_seq.template
DB += AI_scaling.template
DB += AI_scaling_seq.template
DB += description.template

DB += E1210.template
DB += E1214.template
DB += E1240.template
DB += E1241.template
DB += E1242.template

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

